// <auto-generated />
using System;
using System.Text.Json;
using Com.Coppel.Web.Api.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Com.Coppel.Web.Api.Migrations
{
    [DbContext(typeof(SpecDbContext))]
    partial class SpecDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Com.Coppel.Web.Api.Core.Domain.Entities.Criterion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("criteria", (string)null);
                });

            modelBuilder.Entity("Com.Coppel.Web.Api.Core.Domain.Entities.Evaluation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CritFail")
                        .HasColumnType("integer")
                        .HasColumnName("crit_fail");

                    b.Property<int>("CritNa")
                        .HasColumnType("integer")
                        .HasColumnName("crit_na");

                    b.Property<int>("CritPass")
                        .HasColumnType("integer")
                        .HasColumnName("crit_pass");

                    b.Property<bool>("GatePassed")
                        .HasColumnType("boolean")
                        .HasColumnName("gate_passed");

                    b.Property<string>("GateReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("gate_reason");

                    b.Property<string>("Idempotency")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("idempotency");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<string>("OverallStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("overall_status");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("prompt_version");

                    b.Property<JsonDocument>("RawResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_result");

                    b.Property<int>("Retries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retries");

                    b.Property<string>("RevisionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("revision_id");

                    b.Property<int>("ScoreFail")
                        .HasColumnType("integer")
                        .HasColumnName("score_fail");

                    b.Property<int>("ScoreNa")
                        .HasColumnType("integer")
                        .HasColumnName("score_na");

                    b.Property<int>("ScorePass")
                        .HasColumnType("integer")
                        .HasColumnName("score_pass");

                    b.Property<int>("ScoreTotal")
                        .HasColumnType("integer")
                        .HasColumnName("score_total");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OverallStatus");

                    b.HasIndex("RevisionId");

                    b.ToTable("evaluations", (string)null);
                });

            modelBuilder.Entity("Com.Coppel.Web.Api.Core.Domain.Entities.EvaluationCriterion", b =>
                {
                    b.Property<string>("EvaluationId")
                        .HasColumnType("text")
                        .HasColumnName("evaluation_id");

                    b.Property<string>("CriterionId")
                        .HasColumnType("text")
                        .HasColumnName("criterion_id");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<string>("Evidence")
                        .HasColumnType("text")
                        .HasColumnName("evidence");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("status");

                    b.HasKey("EvaluationId", "CriterionId");

                    b.HasIndex("CriterionId");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.ToTable("evaluation_criteria", (string)null);
                });

            modelBuilder.Entity("Com.Coppel.Web.Api.Core.Domain.Entities.Revision", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .HasColumnType("text")
                        .HasColumnName("checksum");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("SpecAuthor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("spec_author");

                    b.Property<DateOnly?>("SpecDate")
                        .HasColumnType("date")
                        .HasColumnName("spec_date");

                    b.Property<string>("SpecVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("spec_version");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("Key", "Number")
                        .IsUnique();

                    b.ToTable("revisions", (string)null);
                });

            modelBuilder.Entity("Com.Coppel.Web.Api.Core.Domain.Entities.Evaluation", b =>
                {
                    b.HasOne("Com.Coppel.Web.Api.Core.Domain.Entities.Revision", "Revision")
                        .WithMany("Evaluations")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("Com.Coppel.Web.Api.Core.Domain.Entities.EvaluationCriterion", b =>
                {
                    b.HasOne("Com.Coppel.Web.Api.Core.Domain.Entities.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Com.Coppel.Web.Api.Core.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany("Criteria")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("Com.Coppel.Web.Api.Core.Domain.Entities.Evaluation", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("Com.Coppel.Web.Api.Core.Domain.Entities.Revision", b =>
                {
                    b.Navigation("Evaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
